### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AndreaMonzini** [Tagirijus/fountain#1]
Hello! thank you for your  work.

I would gently ask under what license is your code? ( i suppose MIT but better to ask)
The original code by "nyousefi"  is under MIT license:
https://github.com/nyousefi/Fountain
The python 3 port by "ColtonProvias" is under MIT too:
https://github.com/ColtonProvias/zymio-fountain

Thank you.

**Comment by Tagirijus** [comment]
Hey Andrea!

Thanks for asking. I never thought about it, to be honest. My bad, sorry. I think the MIT license sounds great here.

So please feel free to understand my code here published under the MIT license, alreay.

I will upload a license text, if I have some time. In the meantime I will keep this issue open to not forget it. Thanks for the hint!

Have a nice day and good luck with my code. (=

Manuel

**Comment by AndreaMonzini** [comment]
Thank you Manuel!
EDIT Add-on for writing screenplays in Blender:
https://github.com/tin2tin/Blender_Screenwriter

**Comment by Tagirijus** [comment]
Haha, nice. I did not even know that Blender has a text editor. Interesting! Good luck with it. (=

**Comment by Tagirijus** [comment]
Closed with commit 3b8251395790d6f771094d9ccf25399c678f8a0b
