### ISSUE TITLE
Empty Line broken?

### ISSUE THREAD

**Issue by tin2tin** [Tagirijus/fountain#2]
I'm trying to get some sort of fountain preview to work in Blender with Andrea, but it seems like no "Empty Line" types are generated. Is this a bug?

**Comment by Tagirijus** [comment]
I did not check it yet, but I will test it, when I have time. Thanks for the report. (=

**Comment by tin2tin** [comment]
Thanks. I'm using Brick and Steel for testing - one of the original fountain test files.

**Comment by tin2tin** [comment]
I'm sorry I was using an old file which didn't contain New Line at all. Sorry. 

Closing this.
