### ISSUE TITLE
Error in splitlines

### ISSUE THREAD

**Issue by tin2tin** [Tagirijus/fountain#4]
If a document without ':' or empty is parsed then it will cause an error

**Comment by Tagirijus** [comment]
I can recreate an error with an empty file, while I cannot recreate an error with a file not containing a `:`.  Please give some more information what you did, how you did it and a sample file would be great.

I am not eager to fix the "empty file" thing at the moment, while I see no logic in parsing an empty file anyway, though.

**Comment by tin2tin** [comment]
This will cause the error:
`Title:
    BRICK & STEEL
    FULL RETIRED

Credit: Written by

Author: Stu Maschwitz

Source: Story by KTM

Draft date: 1/20/2012

Contact:
    Next Level Productions
    1588 Mission Dr.
    Solvang, CA 93463`

Btw. there seems to be a few syntax settings which are not parsed in this fountain file: https://fountain.io/_downloads/Brick%20&%20Steel.fountain like italics, underline, bold and dual dialogue?

**Comment by Tagirijus** [comment]
I do not have any errors, when parsing this file. Markdown styling for italic, underline and bold are being processed on rendering - e.g. with my fountain2pdf script. Regarding this parsing no information about that will be fetched, but the whole markdown-string instead, like in the original script, IIRC.

Regarding dual dialogue: the information about dual dialogue is held in the elements `element.is_dual_dialogue` variable.

Again: I want to repeat myself that I only fetched the original python2 script and made it python3, IIRC. :D ... so sorry for any bugs and errors I also just overlooked and "ported" as well.

**Comment by Tagirijus** [comment]
I just modified the parser so that it can handle empty strings now. Please feel free to re-open the issue, if I missed something. (=

**Comment by tin2tin** [comment]
No no, don't be sorry. I'm just trying to get my head around this stuff, so we can use it for add a screenwriter to Blender using your work. And it is already working great:
https://blenderartists.org/uploads/default/original/4X/c/1/a/c1a0d72c9f2b34a67e067d929d670416a26d6e51.gif

Github changes the styling of my code paste. Could you try with the document from above and delete everyting execept the metadata line?

**Comment by Tagirijus** [comment]
Hehe, wow this looks great already, your GIF! I am pleased that the script helps. Cudos to [Colton J. Provias](https://gist.github.com/ColtonProvias/8232624) though! He did the hard work to port the original C code to python3. I did just a fix and minor tweaks for now. Maybe I will improve the code further some day, though.

Now regarding your issue: yes, I get an error as well, when only parsing the metadata. Thanks for the hint. I am lookign into this.

**Comment by Tagirijus** [comment]
Ok, now it should not throw an error when there are only metadata in the script. Be aware that metadata should not contain double newlines (`\n\n`), since only the first metadata would be accepted as metadata and the other metadata would be interpreted as elements (like action or dialogue).
