### ISSUE TITLE
Dialogues with linebreaks lose "original_content" after first line

### ISSUE THREAD

**Issue by gabrielmontagne** [Tagirijus/fountain#8]
I'm parsing and reconstructing screenplays using this (very useful!) module.
I noticed that on dialogues with multiple lines, the `original_content` was missing lines after the first:

![image](https://github.com/Tagirijus/fountain/assets/95913/a89aeeee-cf90-4d96-9d91-f8632aa52514)

I checked, and you are adding the new `element_text` to the previous Dialog element, but you're not adding the line itself to the original content. 

On my monkey-patched version, I added the following: 

![image](https://github.com/Tagirijus/fountain/assets/95913/7f6b8446-03d4-44cb-a11f-5461b4f758eb)

and it solved my problems.  I'll raise a PR, if you want to bring it in.

**Comment by Tagirijus** [comment]
Hey there. Thanks for pointing that out! I just committed the fix you provided. Thanks for helping out! (=

**Comment by Tagirijus** [comment]
Oh and by the way: credits have to go to Colton J. Provias, who [ported](https://gist.github.com/ColtonProvias/8232624) the [Object-C](https://github.com/nyousefi/Fountain) Fountain parser.
